# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import polar_align_pb2 as polar__align__pb2


class PolarAlignStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartPolarAlign = channel.unary_stream(
                '/polar_align.PolarAlign/StartPolarAlign',
                request_serializer=polar__align__pb2.Request.SerializeToString,
                response_deserializer=polar__align__pb2.PolarError.FromString,
                )
        self.StopPolarAlign = channel.unary_unary(
                '/polar_align.PolarAlign/StopPolarAlign',
                request_serializer=polar__align__pb2.Request.SerializeToString,
                response_deserializer=polar__align__pb2.Response.FromString,
                )


class PolarAlignServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartPolarAlign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPolarAlign(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolarAlignServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartPolarAlign': grpc.unary_stream_rpc_method_handler(
                    servicer.StartPolarAlign,
                    request_deserializer=polar__align__pb2.Request.FromString,
                    response_serializer=polar__align__pb2.PolarError.SerializeToString,
            ),
            'StopPolarAlign': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPolarAlign,
                    request_deserializer=polar__align__pb2.Request.FromString,
                    response_serializer=polar__align__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'polar_align.PolarAlign', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PolarAlign(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartPolarAlign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/polar_align.PolarAlign/StartPolarAlign',
            polar__align__pb2.Request.SerializeToString,
            polar__align__pb2.PolarError.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopPolarAlign(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/polar_align.PolarAlign/StopPolarAlign',
            polar__align__pb2.Request.SerializeToString,
            polar__align__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
