# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: polar_align.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11polar_align.proto\x12\x0bpolar_align\"%\n\nPolarError\x12\n\n\x02ra\x18\x01 \x01(\x02\x12\x0b\n\x03\x64\x65\x63\x18\x02 \x01(\x02\"\t\n\x07Request\"\x1b\n\x08Response\x12\x0f\n\x07stopped\x18\x01 \x01(\x08\x32\x93\x01\n\nPolarAlign\x12\x44\n\x0fStartPolarAlign\x12\x14.polar_align.Request\x1a\x17.polar_align.PolarError\"\x00\x30\x01\x12?\n\x0eStopPolarAlign\x12\x14.polar_align.Request\x1a\x15.polar_align.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'polar_align_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POLARERROR._serialized_start=34
  _POLARERROR._serialized_end=71
  _REQUEST._serialized_start=73
  _REQUEST._serialized_end=82
  _RESPONSE._serialized_start=84
  _RESPONSE._serialized_end=111
  _POLARALIGN._serialized_start=114
  _POLARALIGN._serialized_end=261
# @@protoc_insertion_point(module_scope)
